version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: productos_microservicio-mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./BD/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - productos_network
    ports:
      - 3306:3306

  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mysql
    networks:
      - productos_network

volumes:
  mysql_data:

networks:
  productos_network:
    name: productos_network