version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: productos_microservicio-mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./BD/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - productos_network
    ports:
      - 3306:3306

  app:
    build: .
    ports:
      - 8000:8000

volumes:
  mysql_data:

networks:
  productos_network:
    name: productos_network
